# Generated by Django 2.0.5 on 2018-06-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weather', '0002_auto_20180624_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Age', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Feedback', models.TextField()),
            ],
        ),
    ]
