# Generated by Django 2.2.7 on 2019-11-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weather', '0003_userdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='Age',
            field=models.PositiveIntegerField(),
        ),
    ]
